### ISSUE TITLE
Add supports to thrower internal ramp

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#81]
I suggest adding some cutouts to the top plate of the chassis. This reduces the possibility that the ramp bends. the ramp there is quite thin.:
![image](https://user-images.githubusercontent.com/5435954/147871189-98853ac7-f55b-4a1c-ae1c-a3f5b9ee2718.png)

**Comment by priitro** [comment]
Added supporting top plate body.  Between ramps it is lower because if it`s in a same distance it would resist free ball movement. Throwing motor squeeze's ball between ramps.  Right now distance is 3,55mm
![image](https://user-images.githubusercontent.com/73076712/147931681-a5e8ca97-eb4a-4839-93bc-bc1f05e53b37.png)

![image](https://user-images.githubusercontent.com/73076712/147932061-643e4547-4000-472c-9069-6a214a3af461.png)

**Comment by Akustav** [comment]
I would suggest making the dogbones something like this: 
![image](https://user-images.githubusercontent.com/5435954/148637188-18ef3012-7f55-4152-adbc-e78135871587.png)

Then the ramp is better supported in the direction most forces will apply to it.

**Comment by priitro** [comment]
Made corrections:
![image](https://user-images.githubusercontent.com/73076712/148646185-be7637bc-741c-4754-9b40-7633e27d7928.png)
